# Generated by Django 5.0.1 on 2024-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saved_collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcollections",
            name="dates",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="savedcollections",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
